### ISSUE TITLE
Gradle Plugin not available

### ISSUE THREAD

**Issue by ghostbear** [corunet/scs-multiapi-plugin#137]
It seems that the Gradle plugin is not available due to failing build pipes. 

It would be awesome if it would become available on Gradle Plugin Portal.

**Comment by dianaGomezGar** [comment]
Hi @ghostbear , 

I’m going to mark it as enhancement to tackle this task as soon as possible.  We let you know when it's complete so you can use it.

**Comment by jemacineiras** [comment]
Hi @ghostbear,

problem with pipes is due a validation problem of our domain when pushing to Gradle repo. Those days we are moving under new management/rebranding, meaning new packaging name. So we are not planing to handle this quite soon. 
But, If you need it, we can find an intermediate solution.

Cheers

**Comment by jemacineiras** [comment]
HI @ghostbear,

Gradle plugin 4.2.2 had been deployed and accepted in Gradle Portal. Do you mind to test if it works for you?

Cheers

**Comment by ghostbear** [comment]
Hi @jemacineiras 

Thanks for the quick work 👍🏽. I'm able to use the plugin in my project. However, I'm facing a few issues with generating code from AsyncAPI specifications, OpenAPI specifications seem to work fine. And I will open a new issue about it if I'm not able to resolve it on my end. 

Yet again thanks for the quick work!

Cheers
